# Generated by Django 5.1.3 on 2024-12-09 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=255)),
                ('uz', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='vocab/audio/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabs', to='apps.unit')),
            ],
        ),
    ]
